apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::890529044106:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-6Y7XW0GGJGZK
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::890529044106:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-26T18:03:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1468"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 35da63b7-6322-4642-8abf-8104c3a91fce
