apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::890529044106:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-DMOTPTBZNVA2
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::890529044106:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-25T13:53:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1604"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: d89876b9-638e-46f4-b2bb-b32dc7103999
